/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qffweather_android_myjni_JniTest */

#ifndef _Included_com_qffweather_android_myjni_JniTest
#define _Included_com_qffweather_android_myjni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qffweather_android_myjni_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qffweather_android_myjni_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     com_qffweather_android_myjni_JniTest
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qffweather_android_myjni_JniTest_set
  (JNIEnv *, jobject, jstring);//jstring代表set方法的String类型参数

#ifdef __cplusplus
}
#endif
#endif
/**JNIEnv*:表示一个指向JNI环境的指针，可以通过它来访问JNI提供的接口方法
    jobject:表示java对象中的this
    JNIEXPORT 和JNICALL:他们是JNI忠所定义的宏
*/